studio69_v.1-STAGE/STUDIO69/STUDIO69/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('promotions.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

studio69_v.1-STAGE/STUDIO69/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

studio69_v.1-STAGE/STUDIO69/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
]

studio69_v.1-STAGE/STUDIO69/promotions/urls.py
from django.urls import path
from . import views

app_name = 'promotions'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

studio69_v.1-STAGE/STUDIO69/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

studio69_v.1-STAGE/STUDIO69/cart/models.py
from django.db import models

# Create your models here.

studio69_v.1-STAGE/STUDIO69/cart/forms.py
from django import forms
from shop.models import *

#   Исправить существующий цикл: покупка максимального доступного кол-во
PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(len(Product.objects.all()))
] # Тут надо проверки по наличию и конкретным товарам!


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

studio69_v.1-STAGE/STUDIO69/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from promotions.forms import CouponApplyForm


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True
            }
        )
    coupon_apply_form = CouponApplyForm()
    return render(
        request,
        'cart/detail.html',
        {
            'cart': cart,
            'coupon_apply_form': coupon_apply_form
        }
    )

studio69_v.1-STAGE/STUDIO69/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Моя корзина
{% endblock %}

{% block content %}
<h1>Моя корзина</h1>
<table class="cart">
<thead>
    <tr>
    <th>Изображение</th>
    <th>Товар</th>
    <th>Кол-во</th>
    <th>Удалить</th>
    <th>Цена за шт.</th>
    <th>Цена</th>
    </tr>
</thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}
                            {{ product.image.url }}
                          {% else %}
                            {% static 'img/not_found.png' %}
                          {% endif %}">
            </a>
        </td>
        <td>{{ product.title }}</td>
        <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Добавить">
                {% csrf_token %}
            </form>
        </td>
        <td>
            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
            <input type="submit" value="Удалить">
            {% csrf_token %}
            </form>
        </td>
        <td class="num">{{ item.price }}</td>
        <td class="num">{{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    {% if cart.coupon %}
    <tr class="subtotal">
        <td>Subtotal</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
    </tr>
    <tr>
        <td>
            "{{ cart.coupon.code }}" coupon
            ({{ cart.coupon.discount }}% off)
        </td>
        <td colspan="4"></td>
        <td class="num neg">
            – {{ cart.get_discount|floatformat:2 }}
        </td>
    </tr>
    {% endif %}
    <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price_after_discount|floatformat:2 }}</td>
    </tr>
    </tbody>
</table>
<p>Использовать подарочный купон:</p>
<form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
        <input type="submit" value="Использовать">
    {% csrf_token %}
</form>

<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">Продолжить</a>
    <a href="{% url 'orders:order_create' %}" class="button">Заказать</a>
</p>
{% endblock %}