studio69_v.1-STAGE/STUDIO69/STUDIO69/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('promotions.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

studio69_v.1-STAGE/STUDIO69/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

studio69_v.1-STAGE/STUDIO69/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

studio69_v.1-STAGE/STUDIO69/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    title = models.CharField(
        max_length=128,
        verbose_name='Название'
    )
    slug = models.SlugField(
        max_length=128,
        unique=True,
        verbose_name='Символьный ID'
    )

    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category',
            args=[self.slug]
        )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        indexes = [
            models.Index(fields=['title']),
        ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    title = models.CharField(
        max_length=128,
        verbose_name='Название'
    )
    slug = models.SlugField(
        max_length=128,
        verbose_name='Символьный ID'
    )
    image = models.ImageField(
        upload_to='coffee/%Y/%m/%d',
        blank=True,
        verbose_name='Изображение'
    )
    description = models.TextField(
        blank=True,
        verbose_name='Описание'
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Цена'
    )
    available = models.BooleanField(
        default=True,
        verbose_name='Наличие?'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлен'
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Изменен'
    )

    category = models.ForeignKey(
        'Category',
        blank=True,
        related_name='products',
        on_delete=models.CASCADE,
        verbose_name='Категория'
    )

    def get_absolute_url(self):
        return reverse(
            'shop:product_detail',
            args=[self.id, self.slug]
        )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['title']),
            models.Index(fields=['-created']),
        ]

        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

studio69_v.1-STAGE/STUDIO69/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import CartAddProductForm


# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(
        available=True
    )
    if category_slug:
        category = get_object_or_404(
            Category,
            slug=category_slug,
        )
        products = products.filter(
            category=category
        )
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products
        }
    )


def product_detail(request, id, slug):
    cart_product_form = CartAddProductForm()
    product = get_object_or_404(
        Product,
        id=id,
        slug=slug,
        available=True
    )

    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form
        }
    )

studio69_v.1-STAGE/STUDIO69/templates/shop/includes/footer.html
<footer class="footer">
    <p>Lorem ipsum dolor.</p>
</footer>

studio69_v.1-STAGE/STUDIO69/templates/shop/includes/header.html
{% load static %}
<header class="header">
    <div class="header__inner">
        <div class="container">
            <div class="header__item">
                <div class="header__logo">
                    <a href="{% url 'shop:product_list' %}" class="logo__link">
                        <img src="{% static 'img/logo.png' %}" alt="логотип" class="logo">
                    </a>
                </div>
                <nav class="header__nav">
                    <a href="{% url 'shop:product_list' %}" class="header__nav-link">Главная</a>
                    <a href="#" class="header__nav-link">Оптовые покупки</a>
                    <a href="#" class="header__nav-link">Блог</a>
                    <a href="#" class="header__nav-link">О нас</a>
                </nav>

                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                        Моя корзина:
                        <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} Товар{{ total_items|pluralize }},
                            {{ cart.get_total_price }}
                        </a>
                        {% elif not order %}
                            Корзина пуста
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
</header>